


export const kanbanMessages = {
    'en': {
        'addFilter': '+ Add filter',
        'and': 'And',
        'apply': 'Apply',
        'booleanFirst': '☐',
        'booleanLast': '☑',
        'cancel': 'Cancel',
        'CONTAINS': 'contains',
        'CONTAINS_CASE_SENSITIVE': 'contains (case sensitive)',
        'dateFirst': '1',
        'dateLast': '9',
        'DOES_NOT_CONTAIN': 'does not contain',
        'DOES_NOT_CONTAIN_CASE_SENSITIVE': 'does not contain (case sensitive)',
        'EMPTY': 'empty',
        'ENDS_WITH': 'ends with',
        'ENDS_WITH_CASE_SENSITIVE': 'ends with (case sensitive)',
        'EQUAL': 'equal',
        'EQUAL_CASE_SENSITIVE': 'equal (case sensitive)',
        'filter': 'Filter',
        'filteredByMultiple': '{{n}} filters',
        'filteredByOne': '1 filter',
        'filterValuePlaceholder': 'Value',
        'find': 'Find a field',
        'findInView': 'Find in view',
        'firstBy': 'Sort by',
        'found': '{{nth}} of {{n}}',
        'from': 'from',
        'GREATER_THAN': 'greater than',
        'GREATER_THAN_OR_EQUAL': 'greater than or equal',
        'LESS_THAN': 'less than',
        'LESS_THAN_OR_EQUAL': 'less than or equal',
        'noFilters': 'No filters applied',
        'noResults': 'No results',
        'noSorting': 'No sorting applied',
        'NOT_EMPTY': 'not empty',
        'NOT_EQUAL': 'not equal',
        'NOT_NULL': 'not null',
        'NULL': 'null',
        'numberFirst': '1',
        'numberLast': '9',
        'ok': 'OK',
        'or': 'Or',
        'pickAnother': 'Pick another field to sort by',
        'sort': 'Sort',
        'sortedByMultiple': 'Sorted by {{n}} fields',
        'sortedByOne': 'Sorted by 1 field',
        'STARTS_WITH': 'starts with',
        'STARTS_WITH_CASE_SENSITIVE': 'starts with (case sensitive)',
        'stringFirst': 'A',
        'stringLast': 'Z',
        'thenBy': 'then by',
        'where': 'Where',
        'actionsIcon': 'Actions icon',
        'addNewStatus': 'Add new column',
        // 'addNewStatus': 'New status',
        'addNewTask': 'Add new task',
        'addSubtask': 'Add subtask',
        'assignedTo': 'Assigned to',
        'checklist': 'Checklist',
        'color': 'Color',
        'commentsIcon': 'Comments icon',
        'copy': 'Copy',
        'customize': 'Customize tasks',
        'dueDate': 'Due date',
        'edit': 'Edit',
        'editTask': 'Edit task "{{taskId}}"',
        'high': 'High',
        'low': 'Low',
        'newComment': 'New comment',
        'newSubtask': 'New subtask',
        'normal': 'Normal',
        'priority': 'Priority',
        'priorityIcon': 'Priority icon',
        'progress': 'Progress',
        'promptComment': 'Are you sure you want to remove this comment?',
        'promptTask': 'Are you sure you want to remove the task "{{taskText}}"?',
        'remove': 'Remove',
        'removeSubtask': 'Remove subtask',
        'send': 'Send',
        'startDate': 'Start date',
        'status': 'Status',
        'swimlane': 'Swimlane',
        'tags': 'Tags',
        'text': 'Text',
        'userId': 'User ID',
        'userIcon': 'User icon'
    }
}